{% set name = "djangocms-icon" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djangocms-icon-{{ version }}.tar.gz
  sha256: 1a356c07e4fd89c31919f440300f9f3d80a951491a41545285fe5cf22e59d62d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django-cms >=3.10
    - djangocms-attributes-field >=1

test:
  imports:
    - djangocms_icon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/django-cms/djangocms-icon
  summary: Adds icon plugin to django CMS.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
